# Azure DevOps pipeline to release a new version and deploy to production.

variables:
  NODE_VERSION: '12.19.1'
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  # Configuration to run the healthcheck container
  HEALTHCHECK_CONTAINER_RG: 'io-p-rg-common'
  HEALTHCHECK_CONTAINER_VNET: 'io-p-vnet-common'
  HEALTHCHECK_CONTAINER_SUBNET: 'azure-devops' 
  HEALTHCHECK_PATH: 'api/bonus-vacanze/v1/info'


parameters:
  - name: 'RELEASE_SEMVER'
    displayName: 'When packing a release, define the version bump to apply'
    type: string
    values:
      - major
      - minor
      - patch
    default: minor

# Only manual activations are intended
trigger: none
pr: none

# This pipeline has been implemented to be run on hosted agent pools based both
# on 'windows' and 'ubuntu' virtual machine images and using the scripts defined
# in the package.json file. Since we are deploying on Azure functions on Windows
# runtime, the pipeline is currently configured to use a Windows hosted image for
# the build and deploy.
pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v4
      endpoint: 'pagopa'
    
    - repository: templates
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/heads/171728280_client_SDK_generation
      endpoint: 'pagopa'

stages:

  - stage: Release
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: make_release
        steps:
          - script: |
              echo "Ciao.. questo è un test"
            displayName: 'Fake release step'

  
  

  - stage: Publish Client SDK to NPM
    dependsOn: []
    jobs:
      - job: publish_SDK   
        
        steps:
        # Template for generating and deploying client SDk to NPM
        - template: templates/client-sdk-release/template.yaml@templates
          parameters:
            openapiSpecPath: 'openapi/index.yaml'
     
 